// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.

package apicontract

type Operation struct {
	Method string
	Path   string
}

const SourceSHA256 = "d3c8bb75b1b14fdb3e4046e9d86fe2f087b0c52d385216cd926f1798bdd0b308"

var Operations = map[string]Operation{
	"acceptApplicationDeploymentPlan":           {Method: "PUT", Path: "/api/v1/apps/{appId}/deployment-plan"},
	"approveApplicationDeploymentPlanMigration": {Method: "POST", Path: "/api/v1/apps/{appId}/deployment-plan/migration-approval"},
	"bootstrap":                       {Method: "POST", Path: "/api/v1/auth/bootstrap"},
	"bootstrapStatus":                 {Method: "GET", Path: "/api/v1/auth/bootstrap/status"},
	"cancelJob":                       {Method: "POST", Path: "/api/v1/jobs/{jobId}/cancel"},
	"createApplication":               {Method: "POST", Path: "/api/v1/apps"},
	"deployApplication":               {Method: "POST", Path: "/api/v1/apps/{appId}/deployments"},
	"deployRelease":                   {Method: "POST", Path: "/api/v1/apps/{appId}/releases/{releaseId}/deployments"},
	"disconnectSourceConnection":      {Method: "DELETE", Path: "/api/v1/source-connections/{connectionId}"},
	"doctor":                          {Method: "GET", Path: "/api/v1/system/doctor"},
	"getApplication":                  {Method: "GET", Path: "/api/v1/apps/{appId}"},
	"getApplicationAutoDeploy":        {Method: "GET", Path: "/api/v1/apps/{appId}/auto-deploy"},
	"getApplicationConfiguration":     {Method: "GET", Path: "/api/v1/apps/{appId}/configuration"},
	"getApplicationDeploymentPlan":    {Method: "GET", Path: "/api/v1/apps/{appId}/deployment-plan"},
	"getJob":                          {Method: "GET", Path: "/api/v1/jobs/{jobId}"},
	"getRelayStatus":                  {Method: "GET", Path: "/api/v1/relay/status"},
	"grantRuntimeApproval":            {Method: "POST", Path: "/api/v1/apps/{appId}/runtime-approvals"},
	"inspectImport":                   {Method: "POST", Path: "/api/v1/apps/import/inspect"},
	"listApplications":                {Method: "GET", Path: "/api/v1/apps"},
	"listDeployments":                 {Method: "GET", Path: "/api/v1/apps/{appId}/deployments"},
	"listGitHubBranches":              {Method: "GET", Path: "/api/v1/source-connections/{connectionId}/github/installations/{installationId}/repositories/{repositoryId}/branches"},
	"listGitHubInstallations":         {Method: "GET", Path: "/api/v1/source-connections/{connectionId}/github/installations"},
	"listGitHubRepositories":          {Method: "GET", Path: "/api/v1/source-connections/{connectionId}/github/installations/{installationId}/repositories"},
	"listJobEvents":                   {Method: "GET", Path: "/api/v1/jobs/{jobId}/events"},
	"listJobs":                        {Method: "GET", Path: "/api/v1/jobs"},
	"listMachines":                    {Method: "GET", Path: "/api/v1/machines"},
	"listReleases":                    {Method: "GET", Path: "/api/v1/apps/{appId}/releases"},
	"listRuntimeApprovals":            {Method: "GET", Path: "/api/v1/apps/{appId}/runtime-approvals"},
	"listServices":                    {Method: "GET", Path: "/api/v1/apps/{appId}/services"},
	"listSourceConnections":           {Method: "GET", Path: "/api/v1/source-connections"},
	"login":                           {Method: "POST", Path: "/api/v1/auth/sessions"},
	"logout":                          {Method: "DELETE", Path: "/api/v1/auth/sessions/current"},
	"me":                              {Method: "GET", Path: "/api/v1/auth/me"},
	"pollGitHubDeviceConnection":      {Method: "POST", Path: "/api/v1/source-connections/{connectionId}/device/poll"},
	"pollRelayEnrollment":             {Method: "POST", Path: "/api/v1/relay/enrollments/{enrollmentId}/poll"},
	"refreshSourceConnection":         {Method: "POST", Path: "/api/v1/source-connections/{connectionId}/refresh"},
	"removeRelayBinding":              {Method: "DELETE", Path: "/api/v1/relay/bindings/{bindingId}"},
	"replaceApplicationConfiguration": {Method: "PUT", Path: "/api/v1/apps/{appId}/configuration"},
	"restartApplication":              {Method: "POST", Path: "/api/v1/apps/{appId}/restart"},
	"resumeApplicationAutoDeploy":     {Method: "POST", Path: "/api/v1/apps/{appId}/auto-deploy/resume"},
	"resumeJob":                       {Method: "POST", Path: "/api/v1/jobs/{jobId}/resume"},
	"revokeRuntimeApproval":           {Method: "DELETE", Path: "/api/v1/apps/{appId}/runtime-approvals/{approvalId}"},
	"rotateCSRF":                      {Method: "GET", Path: "/api/v1/auth/csrf"},
	"startApplication":                {Method: "POST", Path: "/api/v1/apps/{appId}/start"},
	"startGitHubDeviceConnection":     {Method: "POST", Path: "/api/v1/source-connections/github/device"},
	"startRelayEnrollment":            {Method: "POST", Path: "/api/v1/relay/enrollments"},
	"startRelayKeyRotation":           {Method: "POST", Path: "/api/v1/relay/key-rotations"},
	"stopApplication":                 {Method: "POST", Path: "/api/v1/apps/{appId}/stop"},
	"streamJobEvents":                 {Method: "GET", Path: "/api/v1/jobs/{jobId}/events/stream"},
	"streamLogs":                      {Method: "GET", Path: "/api/v1/apps/{appId}/logs/stream"},
	"systemStatus":                    {Method: "GET", Path: "/api/v1/system/status"},
	"updateApplicationAutoDeploy":     {Method: "PUT", Path: "/api/v1/apps/{appId}/auto-deploy"},
}

type AcceptDeploymentPlanRequest struct {
	CandidateID                         string                         `json:"candidateId"`
	Components                          []DeploymentPlanComponentInput `json:"components"`
	ExpectedCandidateDigest             string                         `json:"expectedCandidateDigest"`
	ExpectedRevisionNumber              int64                          `json:"expectedRevisionNumber"`
	ExpectedSourceStructuralFingerprint string                         `json:"expectedSourceStructuralFingerprint"`
	InstallBehavior                     string                         `json:"installBehavior"`
	MigrationCommand                    string                         `json:"migrationCommand"`
	PackageManager                      string                         `json:"packageManager"`
}

type AnalysisAdvancedInput struct {
	ComponentID string `json:"componentId"`
	Field       string `json:"field"`
	Reason      string `json:"reason"`
	Required    bool   `json:"required"`
}

type AnalysisCommand struct {
	Command          string             `json:"command,omitempty"`
	Confidence       string             `json:"confidence,omitempty"`
	EnvironmentKeys  []string           `json:"environmentKeys,omitempty"`
	Evidence         []AnalysisEvidence `json:"evidence"`
	Origin           string             `json:"origin,omitempty"`
	Phase            string             `json:"phase,omitempty"`
	Present          bool               `json:"present"`
	Provenance       string             `json:"provenance,omitempty"`
	WorkingDirectory string             `json:"workingDirectory,omitempty"`
}

type AnalysisComponent struct {
	Build                 AnalysisCommand     `json:"build,omitempty"`
	Evidence              []AnalysisEvidence  `json:"evidence"`
	Findings              []AnalysisFinding   `json:"findings"`
	Framework             string              `json:"framework"`
	HealthProbe           AnalysisHealthProbe `json:"healthProbe,omitempty"`
	ID                    string              `json:"id"`
	InternalPort          AnalysisValue       `json:"internalPort,omitempty"`
	Kind                  string              `json:"kind"`
	Migration             AnalysisCommand     `json:"migration,omitempty"`
	MigrationFingerprint  string              `json:"migrationFingerprint"`
	Name                  string              `json:"name"`
	Origin                string              `json:"origin"`
	RootDirectory         string              `json:"rootDirectory"`
	Run                   AnalysisCommand     `json:"run,omitempty"`
	StaticOutputDirectory string              `json:"staticOutputDirectory"`
}

type AnalysisEvidence struct {
	Code   string `json:"code"`
	Detail string `json:"detail,omitempty"`
	Field  string `json:"field,omitempty"`
	Path   string `json:"path,omitempty"`
}

type AnalysisFinding struct {
	Code     string `json:"code"`
	Field    string `json:"field,omitempty"`
	Message  string `json:"message"`
	Path     string `json:"path,omitempty"`
	Severity string `json:"severity"`
}

type AnalysisHealthProbe struct {
	Confidence string             `json:"confidence,omitempty"`
	Evidence   []AnalysisEvidence `json:"evidence"`
	Method     string             `json:"method,omitempty"`
	Origin     string             `json:"origin,omitempty"`
	Path       string             `json:"path,omitempty"`
	Present    bool               `json:"present"`
	Provenance string             `json:"provenance,omitempty"`
}

type AnalysisPackageManager struct {
	Confidence string             `json:"confidence,omitempty"`
	Evidence   []AnalysisEvidence `json:"evidence"`
	Lockfile   string             `json:"lockfile,omitempty"`
	Name       string             `json:"name,omitempty"`
	Origin     string             `json:"origin,omitempty"`
	Present    bool               `json:"present"`
	Provenance string             `json:"provenance,omitempty"`
	Version    string             `json:"version,omitempty"`
}

type AnalysisValue struct {
	Confidence string             `json:"confidence,omitempty"`
	Evidence   []AnalysisEvidence `json:"evidence"`
	Origin     string             `json:"origin,omitempty"`
	Present    bool               `json:"present"`
	Provenance string             `json:"provenance,omitempty"`
	Value      string             `json:"value,omitempty"`
}

type Application struct {
	CreatedAt   string        `json:"createdAt"`
	Description string        `json:"description"`
	ID          string        `json:"id"`
	MachineName string        `json:"machineName"`
	Name        string        `json:"name"`
	Slug        string        `json:"slug"`
	Source      SourceSummary `json:"source"`
	Status      string        `json:"status"`
}

type ApplicationAutoDeployStatus struct {
	ActiveJobID               string        `json:"activeJobId,omitempty"`
	ActiveSha                 string        `json:"activeSha"`
	ApplicationID             string        `json:"applicationId"`
	Enabled                   bool          `json:"enabled"`
	LastSuccessfulDeployedSha string        `json:"lastSuccessfulDeployedSha"`
	LatestResolvedSha         string        `json:"latestResolvedSha"`
	NextRetryAt               string        `json:"nextRetryAt,omitempty"`
	PauseCode                 string        `json:"pauseCode,omitempty"`
	PausedSha                 string        `json:"pausedSha"`
	RetryAttempt              int           `json:"retryAttempt"`
	Revision                  int64         `json:"revision"`
	Source                    SourceSummary `json:"source"`
	SourceScopeActive         bool          `json:"sourceScopeActive"`
	State                     string        `json:"state"`
	UpdatedAt                 string        `json:"updatedAt"`
}

type ApplicationConfiguration struct {
	Entries        []ConfigurationEntry `json:"entries"`
	RevisionID     string               `json:"revisionId,omitempty"`
	RevisionNumber int64                `json:"revisionNumber"`
	UpdatedAt      string               `json:"updatedAt,omitempty"`
}

type ApplicationList struct {
	Items []Application `json:"items"`
}

type ApproveDeploymentPlanMigrationRequest struct {
	ExpectedApprovalRevision int64  `json:"expectedApprovalRevision"`
	RevisionID               string `json:"revisionId"`
	RevisionNumber           int64  `json:"revisionNumber"`
}

type BootstrapRequest struct {
	Passphrase string `json:"passphrase"`
	Token      string `json:"token"`
	Username   string `json:"username"`
}

type BootstrapStatus struct {
	BootstrapRequired bool `json:"bootstrapRequired"`
}

type CSRFResponse struct {
	CSRFToken string `json:"csrfToken"`
}

type Capabilities struct {
	ComposeRuntime    bool `json:"composeRuntime"`
	FakeRuntime       bool `json:"fakeRuntime"`
	GeneratedRuntime  bool `json:"generatedRuntime"`
	GithubConnections bool `json:"githubConnections"`
}

type ConfigurationEntry struct {
	Key       string `json:"key"`
	Sensitive bool   `json:"sensitive"`
	Value     string `json:"value,omitempty"`
}

type ConfigurationValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CreateApplicationRequest struct {
	Description  string       `json:"description,omitempty"`
	GithubSource GitHubSource `json:"githubSource,omitempty"`
	MachineID    string       `json:"machineId,omitempty"`
	Name         string       `json:"name"`
	SourcePath   string       `json:"sourcePath,omitempty"`
}

type DeployReleaseRequest struct {
	ConfigurationMode string `json:"configurationMode"`
}

type Deployment struct {
	ActualConfigurationRevisionID     string          `json:"actualConfigurationRevisionId,omitempty"`
	ActualConfigurationRevisionNumber int64           `json:"actualConfigurationRevisionNumber"`
	AppID                             string          `json:"appId"`
	ConfigurationMode                 string          `json:"configurationMode"`
	DeploymentPlanRevisionID          string          `json:"deploymentPlanRevisionId,omitempty"`
	DeploymentPlanRevisionNumber      int64           `json:"deploymentPlanRevisionNumber"`
	DiagnosticCode                    string          `json:"diagnosticCode,omitempty"`
	FailureSummary                    string          `json:"failureSummary,omitempty"`
	Findings                          []PolicyFinding `json:"findings"`
	FinishedAt                        string          `json:"finishedAt,omitempty"`
	ID                                string          `json:"id"`
	JobID                             string          `json:"jobId,omitempty"`
	MachineID                         string          `json:"machineId,omitempty"`
	ReleaseID                         string          `json:"releaseId,omitempty"`
	RuntimeStrategy                   string          `json:"runtimeStrategy"`
	StartedAt                         string          `json:"startedAt,omitempty"`
	Status                            string          `json:"status"`
}

type DeploymentList struct {
	Items []Deployment `json:"items"`
}

type DeploymentPlanCandidate struct {
	AdvancedInputs []AnalysisAdvancedInput `json:"advancedInputs"`
	Components     []AnalysisComponent     `json:"components"`
	ConfigPath     string                  `json:"configPath"`
	Digest         string                  `json:"digest"`
	Evidence       []AnalysisEvidence      `json:"evidence"`
	Findings       []AnalysisFinding       `json:"findings"`
	ID             string                  `json:"id"`
	Install        AnalysisCommand         `json:"install,omitempty"`
	Kind           string                  `json:"kind"`
	MissingFields  []string                `json:"missingFields"`
	NodeVersion    AnalysisValue           `json:"nodeVersion"`
	Origin         string                  `json:"origin"`
	PackageManager AnalysisPackageManager  `json:"packageManager"`
	RootDirectory  string                  `json:"rootDirectory"`
	Status         string                  `json:"status"`
}

type DeploymentPlanComponent struct {
	BuildCommand    string `json:"buildCommand"`
	HealthProbe     string `json:"healthProbe"`
	InstallBehavior string `json:"installBehavior"`
	InternalPort    int    `json:"internalPort"`
	Name            string `json:"name"`
	NodeVersion     string `json:"nodeVersion"`
	PackageManager  string `json:"packageManager"`
	Role            string `json:"role"`
	RootDirectory   string `json:"rootDirectory"`
	RunCommand      string `json:"runCommand"`
}

type DeploymentPlanComponentInput struct {
	BuildCommand string `json:"buildCommand"`
	ComponentID  string `json:"componentId"`
	HealthProbe  string `json:"healthProbe"`
	InternalPort int    `json:"internalPort"`
	NodeVersion  string `json:"nodeVersion"`
	RunCommand   string `json:"runCommand"`
}

type DeploymentPlanDetector struct {
	Name                        string `json:"name"`
	SourceStructuralFingerprint string `json:"sourceStructuralFingerprint"`
	Version                     string `json:"version"`
}

type DeploymentPlanFieldProvenance struct {
	Confidence int      `json:"confidence"`
	Evidence   []string `json:"evidence"`
	Field      string   `json:"field"`
	Origin     string   `json:"origin"`
}

type DeploymentPlanMigration struct {
	ApprovalStatus  string   `json:"approvalStatus,omitempty"`
	ApprovedAt      string   `json:"approvedAt,omitempty"`
	ApprovedBy      string   `json:"approvedBy,omitempty"`
	Command         string   `json:"command,omitempty"`
	ComponentName   string   `json:"componentName,omitempty"`
	EnvironmentKeys []string `json:"environmentKeys,omitempty"`
	EvidenceDigest  string   `json:"evidenceDigest,omitempty"`
	Present         bool     `json:"present"`
	RootDirectory   string   `json:"rootDirectory,omitempty"`
}

type DeploymentPlanRevision struct {
	AcceptedAt      string                          `json:"acceptedAt,omitempty"`
	AcceptedBy      string                          `json:"acceptedBy,omitempty"`
	CanonicalDigest string                          `json:"canonicalDigest"`
	Components      []DeploymentPlanComponent       `json:"components"`
	Detector        DeploymentPlanDetector          `json:"detector"`
	FieldProvenance []DeploymentPlanFieldProvenance `json:"fieldProvenance"`
	Migration       DeploymentPlanMigration         `json:"migration"`
	RevisionID      string                          `json:"revisionId,omitempty"`
	RevisionNumber  int64                           `json:"revisionNumber"`
	Source          DeploymentPlanSource            `json:"source"`
	State           string                          `json:"state"`
	Strategy        string                          `json:"strategy"`
}

type DeploymentPlanSource struct {
	Provider       string `json:"provider"`
	RepositoryID   int64  `json:"repositoryId"`
	ResolvedDigest string `json:"resolvedDigest"`
}

type DetectedService struct {
	BuildContext string `json:"buildContext,omitempty"`
	Image        string `json:"image,omitempty"`
	Name         string `json:"name"`
}

type Diagnostics struct {
	Architecture      string        `json:"architecture"`
	CaddyManaged      bool          `json:"caddyManaged"`
	ClientAvailable   bool          `json:"clientAvailable"`
	ComposeAvailable  bool          `json:"composeAvailable"`
	ComposeDetail     string        `json:"composeDetail"`
	ComposeVersion    string        `json:"composeVersion"`
	DaemonRunning     bool          `json:"daemonRunning"`
	DockerDetail      string        `json:"dockerDetail"`
	DockerVersion     string        `json:"dockerVersion"`
	EngineReady       bool          `json:"engineReady"`
	OS                string        `json:"os"`
	Resources         HostResources `json:"resources"`
	StartupLimitation string        `json:"startupLimitation"`
}

type DoctorCheck struct {
	Detail string `json:"detail"`
	Name   string `json:"name"`
	OK     bool   `json:"ok"`
}

type DoctorResponse struct {
	Checks            []DoctorCheck `json:"checks"`
	StartupLimitation string        `json:"startupLimitation"`
}

type GitHubBranch struct {
	Name      string `json:"name"`
	Protected bool   `json:"protected"`
	Sha       string `json:"sha"`
}

type GitHubBranchPage struct {
	Items   []GitHubBranch `json:"items"`
	Page    int            `json:"page"`
	PerPage int            `json:"perPage"`
}

type GitHubDeviceAuthorization struct {
	ConnectionID        string `json:"connectionId"`
	ExpiresAt           string `json:"expiresAt"`
	InstallUrl          string `json:"installUrl"`
	PollIntervalSeconds int    `json:"pollIntervalSeconds"`
	UserCode            string `json:"userCode"`
	VerificationUri     string `json:"verificationUri"`
}

type GitHubInstallation struct {
	AccountLogin        string `json:"accountLogin"`
	AccountType         string `json:"accountType"`
	CachedAt            string `json:"cachedAt"`
	ID                  int64  `json:"id"`
	RepositorySelection string `json:"repositorySelection"`
	SuspendedAt         string `json:"suspendedAt,omitempty"`
	TargetType          string `json:"targetType"`
}

type GitHubInstallationPage struct {
	Items      []GitHubInstallation `json:"items"`
	Page       int                  `json:"page"`
	PerPage    int                  `json:"perPage"`
	TotalCount int                  `json:"totalCount"`
}

type GitHubRepository struct {
	Archived      bool   `json:"archived"`
	DefaultBranch string `json:"defaultBranch"`
	Disabled      bool   `json:"disabled"`
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	Owner         string `json:"owner"`
	Private       bool   `json:"private"`
}

type GitHubRepositoryPage struct {
	Items      []GitHubRepository `json:"items"`
	Page       int                `json:"page"`
	PerPage    int                `json:"perPage"`
	TotalCount int                `json:"totalCount"`
}

type GitHubSource struct {
	Branch         string `json:"branch"`
	ComposePath    string `json:"composePath,omitempty"`
	ConnectionID   string `json:"connectionId"`
	InstallationID int64  `json:"installationId"`
	RepositoryID   int64  `json:"repositoryId"`
}

type GrantRuntimeApprovalRequest struct {
	Fingerprint string `json:"fingerprint"`
}

type HostResources struct {
	DiskAvailableBytes   int64 `json:"diskAvailableBytes"`
	DiskTotalBytes       int64 `json:"diskTotalBytes"`
	MemoryAvailableBytes int64 `json:"memoryAvailableBytes"`
	MemoryTotalBytes     int64 `json:"memoryTotalBytes"`
}

type InspectRequest struct {
	GithubSource GitHubSource `json:"githubSource,omitempty"`
	SourcePath   string       `json:"sourcePath,omitempty"`
}

type InspectResponse struct {
	Analysis          SourceAnalysis    `json:"analysis"`
	ComposeCandidates []string          `json:"composeCandidates"`
	Findings          []SourceFinding   `json:"findings"`
	ResolvedSha       string            `json:"resolvedSha,omitempty"`
	Services          []DetectedService `json:"services"`
	Source            SourceSummary     `json:"source"`
}

type Job struct {
	Attempt          int    `json:"attempt"`
	Checkpoint       string `json:"checkpoint"`
	CreatedAt        string `json:"createdAt"`
	ErrorCode        string `json:"errorCode,omitempty"`
	ErrorDetail      string `json:"errorDetail,omitempty"`
	ID               string `json:"id"`
	PauseDisposition string `json:"pauseDisposition,omitempty"`
	Phase            string `json:"phase"`
	Progress         int    `json:"progress"`
	RequestedBy      string `json:"requestedBy,omitempty"`
	ResourceID       string `json:"resourceId"`
	ResourceType     string `json:"resourceType"`
	Status           string `json:"status"`
	Type             string `json:"type"`
	UpdatedAt        string `json:"updatedAt"`
}

type JobEvent struct {
	Attempt   int    `json:"attempt"`
	Code      string `json:"code"`
	ID        int64  `json:"id"`
	JobID     string `json:"jobId"`
	Level     string `json:"level"`
	Message   string `json:"message"`
	Phase     string `json:"phase"`
	Sequence  int    `json:"sequence"`
	Timestamp string `json:"timestamp"`
}

type JobEventList struct {
	Items []JobEvent `json:"items"`
}

type JobList struct {
	Items []Job `json:"items"`
}

type JobMutationResponse struct {
	Created bool `json:"created"`
	Job     Job  `json:"job"`
}

type JobResponse struct {
	Job Job `json:"job"`
}

type LoginRequest struct {
	Passphrase string `json:"passphrase"`
	Username   string `json:"username"`
}

type Machine struct {
	Architecture   string         `json:"architecture"`
	ComposeVersion string         `json:"composeVersion"`
	DockerVersion  string         `json:"dockerVersion"`
	Hostname       string         `json:"hostname"`
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	OS             string         `json:"os"`
	Resources      map[string]any `json:"resources"`
	Status         string         `json:"status"`
}

type MachineList struct {
	Items []Machine `json:"items"`
}

type MeResponse struct {
	User User `json:"user"`
}

type PolicyFinding struct {
	Capability    string `json:"capability"`
	CreatedAt     string `json:"createdAt"`
	DeploymentID  string `json:"deploymentId"`
	Disposition   string `json:"disposition"`
	Fingerprint   string `json:"fingerprint"`
	ID            string `json:"id"`
	PolicyVersion string `json:"policyVersion"`
	Scope         string `json:"scope"`
}

type Problem struct {
	Code      string            `json:"code"`
	Detail    string            `json:"detail"`
	Errors    map[string]string `json:"errors,omitempty"`
	RequestID string            `json:"requestId"`
	Status    int               `json:"status"`
	Title     string            `json:"title"`
	Type      string            `json:"type"`
}

type RelayBindingStatus struct {
	BindingID string `json:"bindingId"`
	State     string `json:"state"`
	UpdatedAt string `json:"updatedAt"`
}

type RelayBindingSummary struct {
	BindingID      string `json:"bindingId"`
	ConnectionID   string `json:"connectionId"`
	InstallationID int64  `json:"installationId"`
	RepositoryID   int64  `json:"repositoryId"`
	State          string `json:"state"`
	UpdatedAt      string `json:"updatedAt"`
}

type RelayEnrollmentStart struct {
	AuthorizationUrl string `json:"authorizationUrl"`
	EnrollmentID     string `json:"enrollmentId"`
	ExpiresAt        string `json:"expiresAt"`
	Status           string `json:"status"`
}

type RelayEnrollmentStatus struct {
	BindingID    string `json:"bindingId,omitempty"`
	CompletedAt  string `json:"completedAt,omitempty"`
	CreatedAt    string `json:"createdAt"`
	EnrollmentID string `json:"enrollmentId"`
	ExpiresAt    string `json:"expiresAt"`
	Status       string `json:"status"`
	UpdatedAt    string `json:"updatedAt"`
}

type RelayKeyRotationStatus struct {
	ExpiresAt  string `json:"expiresAt"`
	RotationID string `json:"rotationId"`
	State      string `json:"state"`
}

type RelayKeyRotationSummary struct {
	ExpiresAt  string `json:"expiresAt,omitempty"`
	InProgress bool   `json:"inProgress"`
	State      string `json:"state,omitempty"`
	UpdatedAt  string `json:"updatedAt,omitempty"`
}

type RelayStatus struct {
	ActiveLeases            int                     `json:"activeLeases"`
	Availability            string                  `json:"availability"`
	DiagnosticsUnavailable  bool                    `json:"diagnosticsUnavailable"`
	ExpiredLeases           int                     `json:"expiredLeases"`
	KeyRotation             RelayKeyRotationSummary `json:"keyRotation"`
	ObserverDropped         int64                   `json:"observerDropped"`
	OldestPendingAgeSeconds int                     `json:"oldestPendingAgeSeconds"`
	Outcome                 string                  `json:"outcome"`
	Paused                  bool                    `json:"paused"`
	PendingCommands         int                     `json:"pendingCommands"`
	ReadModelAvailable      bool                    `json:"readModelAvailable"`
	RemovableBindings       []RelayBindingSummary   `json:"removableBindings"`
	State                   string                  `json:"state"`
}

type Release struct {
	AppID                        string `json:"appId"`
	ArchiveSha256                string `json:"archiveSha256,omitempty"`
	ComposePath                  string `json:"composePath,omitempty"`
	ConfigurationRevisionID      string `json:"configurationRevisionId,omitempty"`
	ConfigurationRevisionNumber  int64  `json:"configurationRevisionNumber"`
	CreatedAt                    string `json:"createdAt"`
	DeploymentPlanRevisionID     string `json:"deploymentPlanRevisionId,omitempty"`
	DeploymentPlanRevisionNumber int64  `json:"deploymentPlanRevisionNumber"`
	ID                           string `json:"id"`
	RepositoryID                 int64  `json:"repositoryId,omitempty"`
	RepositoryName               string `json:"repositoryName,omitempty"`
	RepositoryOwner              string `json:"repositoryOwner,omitempty"`
	ResolvedSha                  string `json:"resolvedSha,omitempty"`
	RuntimeStrategy              string `json:"runtimeStrategy"`
	SourceBranch                 string `json:"sourceBranch,omitempty"`
	SourceCommitSha              string `json:"sourceCommitSha,omitempty"`
	SourceProvider               string `json:"sourceProvider"`
	TrackedRef                   string `json:"trackedRef,omitempty"`
	WorkspaceState               string `json:"workspaceState,omitempty"`
}

type ReleaseList struct {
	Items []Release `json:"items"`
}

type ReplaceApplicationConfigurationRequest struct {
	ExpectedRevisionNumber int64                           `json:"expectedRevisionNumber"`
	Remove                 []string                        `json:"remove"`
	Secrets                []SecretConfigurationValueInput `json:"secrets"`
	Variables              []ConfigurationValueInput       `json:"variables"`
}

type ResumeApplicationAutoDeployRequest struct {
	ExpectedRevision int64 `json:"expectedRevision"`
}

type RuntimeApproval struct {
	AppID         string `json:"appId"`
	Capability    string `json:"capability"`
	Fingerprint   string `json:"fingerprint"`
	GrantedAt     string `json:"grantedAt"`
	GrantedBy     string `json:"grantedBy"`
	ID            string `json:"id"`
	PolicyVersion string `json:"policyVersion"`
	RevokedAt     string `json:"revokedAt,omitempty"`
	RevokedBy     string `json:"revokedBy,omitempty"`
	Scope         string `json:"scope"`
}

type RuntimeApprovalList struct {
	Items []RuntimeApproval `json:"items"`
}

type RuntimeApprovalMutationResponse struct {
	Approval RuntimeApproval `json:"approval"`
	Created  bool            `json:"created"`
}

type RuntimeApprovalResponse struct {
	Approval RuntimeApproval `json:"approval"`
}

type SecretConfigurationValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Service struct {
	ID     string `json:"id"`
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Port   int    `json:"port,omitempty"`
	Status string `json:"status"`
}

type ServiceList struct {
	Items []Service `json:"items"`
}

type SessionResponse struct {
	CSRFToken string `json:"csrfToken"`
	User      User   `json:"user"`
}

type SourceAnalysis struct {
	Candidates            []DeploymentPlanCandidate `json:"candidates"`
	Findings              []AnalysisFinding         `json:"findings"`
	ResolvedDigest        string                    `json:"resolvedDigest"`
	SchemaVersion         string                    `json:"schemaVersion"`
	Source                SourceSummary             `json:"source"`
	StructuralFingerprint string                    `json:"structuralFingerprint"`
}

type SourceConnection struct {
	AccessExpiresAt      string `json:"accessExpiresAt,omitempty"`
	ConnectedAt          string `json:"connectedAt,omitempty"`
	CreatedAt            string `json:"createdAt"`
	CredentialGeneration int64  `json:"credentialGeneration"`
	DisconnectedAt       string `json:"disconnectedAt,omitempty"`
	ID                   string `json:"id"`
	InstallUrl           string `json:"installUrl,omitempty"`
	LastErrorCode        string `json:"lastErrorCode,omitempty"`
	NextPollAt           string `json:"nextPollAt,omitempty"`
	PendingExpiresAt     string `json:"pendingExpiresAt,omitempty"`
	Provider             string `json:"provider"`
	ProviderLogin        string `json:"providerLogin,omitempty"`
	ProviderUserID       string `json:"providerUserId,omitempty"`
	RefreshExpiresAt     string `json:"refreshExpiresAt,omitempty"`
	Status               string `json:"status"`
	UpdatedAt            string `json:"updatedAt"`
}

type SourceConnectionList struct {
	Items []SourceConnection `json:"items"`
}

type SourceFinding struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Path    string `json:"path,omitempty"`
}

type SourceSummary struct {
	ComposePath     string `json:"composePath,omitempty"`
	ConnectionID    string `json:"connectionId,omitempty"`
	InstallationID  int64  `json:"installationId,omitempty"`
	Path            string `json:"path,omitempty"`
	RepositoryID    int64  `json:"repositoryId,omitempty"`
	RepositoryName  string `json:"repositoryName,omitempty"`
	RepositoryOwner string `json:"repositoryOwner,omitempty"`
	ResolvedSha     string `json:"resolvedSha,omitempty"`
	TrackedBranch   string `json:"trackedBranch,omitempty"`
	TrackedRef      string `json:"trackedRef,omitempty"`
	Type            string `json:"type"`
}

type StartRelayEnrollmentRequest struct {
	ConnectionID   string `json:"connectionId"`
	InstallationID int64  `json:"installationId"`
	RepositoryID   int64  `json:"repositoryId"`
}

type SystemStatus struct {
	Capabilities Capabilities `json:"capabilities"`
	Daemon       string       `json:"daemon"`
	Diagnostics  Diagnostics  `json:"diagnostics"`
}

type UpdateApplicationAutoDeployRequest struct {
	Enabled          bool  `json:"enabled"`
	ExpectedRevision int64 `json:"expectedRevision"`
}

type User struct {
	ID       string `json:"id"`
	Role     string `json:"role"`
	Username string `json:"username"`
}
