// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.

package apicontract

type Operation struct {
	Method string
	Path   string
}

const SourceSHA256 = "71ba4e0cdb23cdfac8c57c539f14d71523e1149a7a024e36e04b68293f4b9ecd"

var Operations = map[string]Operation{
	"bootstrap":          {Method: "POST", Path: "/api/v1/auth/bootstrap"},
	"bootstrapStatus":    {Method: "GET", Path: "/api/v1/auth/bootstrap/status"},
	"cancelJob":          {Method: "POST", Path: "/api/v1/jobs/{jobId}/cancel"},
	"createApplication":  {Method: "POST", Path: "/api/v1/apps"},
	"deployApplication":  {Method: "POST", Path: "/api/v1/apps/{appId}/deployments"},
	"doctor":             {Method: "GET", Path: "/api/v1/system/doctor"},
	"getApplication":     {Method: "GET", Path: "/api/v1/apps/{appId}"},
	"getJob":             {Method: "GET", Path: "/api/v1/jobs/{jobId}"},
	"inspectImport":      {Method: "POST", Path: "/api/v1/apps/import/inspect"},
	"listApplications":   {Method: "GET", Path: "/api/v1/apps"},
	"listJobEvents":      {Method: "GET", Path: "/api/v1/jobs/{jobId}/events"},
	"listJobs":           {Method: "GET", Path: "/api/v1/jobs"},
	"listMachines":       {Method: "GET", Path: "/api/v1/machines"},
	"listServices":       {Method: "GET", Path: "/api/v1/apps/{appId}/services"},
	"login":              {Method: "POST", Path: "/api/v1/auth/sessions"},
	"logout":             {Method: "DELETE", Path: "/api/v1/auth/sessions/current"},
	"me":                 {Method: "GET", Path: "/api/v1/auth/me"},
	"restartApplication": {Method: "POST", Path: "/api/v1/apps/{appId}/restart"},
	"rotateCSRF":         {Method: "GET", Path: "/api/v1/auth/csrf"},
	"startApplication":   {Method: "POST", Path: "/api/v1/apps/{appId}/start"},
	"stopApplication":    {Method: "POST", Path: "/api/v1/apps/{appId}/stop"},
	"streamJobEvents":    {Method: "GET", Path: "/api/v1/jobs/{jobId}/events/stream"},
	"streamLogs":         {Method: "GET", Path: "/api/v1/apps/{appId}/logs/stream"},
	"systemStatus":       {Method: "GET", Path: "/api/v1/system/status"},
}

type Application struct {
	CreatedAt   string `json:"createdAt"`
	Description string `json:"description"`
	ID          string `json:"id"`
	MachineName string `json:"machineName"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Status      string `json:"status"`
}

type ApplicationList struct {
	Items []Application `json:"items"`
}

type BootstrapRequest struct {
	Passphrase string `json:"passphrase"`
	Token      string `json:"token"`
	Username   string `json:"username"`
}

type BootstrapStatus struct {
	BootstrapRequired bool `json:"bootstrapRequired"`
}

type CSRFResponse struct {
	CSRFToken string `json:"csrfToken"`
}

type Capabilities struct {
	FakeRuntime bool `json:"fakeRuntime"`
}

type CreateApplicationRequest struct {
	Description string `json:"description,omitempty"`
	MachineID   string `json:"machineId,omitempty"`
	Name        string `json:"name"`
	SourcePath  string `json:"sourcePath,omitempty"`
}

type Diagnostics struct {
	Architecture      string        `json:"architecture"`
	CaddyManaged      bool          `json:"caddyManaged"`
	ClientAvailable   bool          `json:"clientAvailable"`
	ComposeAvailable  bool          `json:"composeAvailable"`
	ComposeDetail     string        `json:"composeDetail"`
	ComposeVersion    string        `json:"composeVersion"`
	DaemonRunning     bool          `json:"daemonRunning"`
	DockerDetail      string        `json:"dockerDetail"`
	DockerVersion     string        `json:"dockerVersion"`
	EngineReady       bool          `json:"engineReady"`
	OS                string        `json:"os"`
	Resources         HostResources `json:"resources"`
	StartupLimitation string        `json:"startupLimitation"`
}

type DoctorCheck struct {
	Detail string `json:"detail"`
	Name   string `json:"name"`
	OK     bool   `json:"ok"`
}

type DoctorResponse struct {
	Checks            []DoctorCheck `json:"checks"`
	StartupLimitation string        `json:"startupLimitation"`
}

type HostResources struct {
	DiskAvailableBytes   int64 `json:"diskAvailableBytes"`
	DiskTotalBytes       int64 `json:"diskTotalBytes"`
	MemoryAvailableBytes int64 `json:"memoryAvailableBytes"`
	MemoryTotalBytes     int64 `json:"memoryTotalBytes"`
}

type InspectRequest struct {
	SourcePath string `json:"sourcePath"`
}

type InspectResponse struct {
	Inspection string `json:"inspection"`
	Message    string `json:"message"`
	Source     string `json:"source"`
}

type Job struct {
	Checkpoint   string `json:"checkpoint"`
	CreatedAt    string `json:"createdAt"`
	ErrorCode    string `json:"errorCode,omitempty"`
	ErrorDetail  string `json:"errorDetail,omitempty"`
	ID           string `json:"id"`
	Phase        string `json:"phase"`
	Progress     int    `json:"progress"`
	ResourceID   string `json:"resourceId"`
	ResourceType string `json:"resourceType"`
	Status       string `json:"status"`
	Type         string `json:"type"`
	UpdatedAt    string `json:"updatedAt"`
}

type JobEvent struct {
	Code      string `json:"code"`
	ID        int64  `json:"id"`
	JobID     string `json:"jobId"`
	Level     string `json:"level"`
	Message   string `json:"message"`
	Phase     string `json:"phase"`
	Sequence  int    `json:"sequence"`
	Timestamp string `json:"timestamp"`
}

type JobEventList struct {
	Items []JobEvent `json:"items"`
}

type JobList struct {
	Items []Job `json:"items"`
}

type JobMutationResponse struct {
	Created bool `json:"created"`
	Job     Job  `json:"job"`
}

type JobResponse struct {
	Job Job `json:"job"`
}

type LoginRequest struct {
	Passphrase string `json:"passphrase"`
	Username   string `json:"username"`
}

type Machine struct {
	Architecture   string         `json:"architecture"`
	ComposeVersion string         `json:"composeVersion"`
	DockerVersion  string         `json:"dockerVersion"`
	Hostname       string         `json:"hostname"`
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	OS             string         `json:"os"`
	Resources      map[string]any `json:"resources"`
	Status         string         `json:"status"`
}

type MachineList struct {
	Items []Machine `json:"items"`
}

type MeResponse struct {
	User User `json:"user"`
}

type Problem struct {
	Code      string            `json:"code"`
	Detail    string            `json:"detail"`
	Errors    map[string]string `json:"errors,omitempty"`
	RequestID string            `json:"requestId"`
	Status    int               `json:"status"`
	Title     string            `json:"title"`
	Type      string            `json:"type"`
}

type Service struct {
	ID     string `json:"id"`
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Port   int    `json:"port,omitempty"`
	Status string `json:"status"`
}

type ServiceList struct {
	Items []Service `json:"items"`
}

type SessionResponse struct {
	CSRFToken string `json:"csrfToken"`
	User      User   `json:"user"`
}

type SystemStatus struct {
	Capabilities Capabilities `json:"capabilities"`
	Daemon       string       `json:"daemon"`
	Diagnostics  Diagnostics  `json:"diagnostics"`
}

type User struct {
	ID       string `json:"id"`
	Role     string `json:"role"`
	Username string `json:"username"`
}
