// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.

package apicontract

type Operation struct {
	Method string
	Path   string
}

const SourceSHA256 = "ed1dd05265640fa1d1b4901f743bb4c37736f057e98cf25161b7f1e0a259f55f"

var Operations = map[string]Operation{
	"bootstrap":          {Method: "POST", Path: "/api/v1/auth/bootstrap"},
	"bootstrapStatus":    {Method: "GET", Path: "/api/v1/auth/bootstrap/status"},
	"cancelJob":          {Method: "POST", Path: "/api/v1/jobs/{jobId}/cancel"},
	"createApplication":  {Method: "POST", Path: "/api/v1/apps"},
	"deployApplication":  {Method: "POST", Path: "/api/v1/apps/{appId}/deployments"},
	"doctor":             {Method: "GET", Path: "/api/v1/system/doctor"},
	"getApplication":     {Method: "GET", Path: "/api/v1/apps/{appId}"},
	"getJob":             {Method: "GET", Path: "/api/v1/jobs/{jobId}"},
	"inspectImport":      {Method: "POST", Path: "/api/v1/apps/import/inspect"},
	"listApplications":   {Method: "GET", Path: "/api/v1/apps"},
	"listJobEvents":      {Method: "GET", Path: "/api/v1/jobs/{jobId}/events"},
	"listJobs":           {Method: "GET", Path: "/api/v1/jobs"},
	"listMachines":       {Method: "GET", Path: "/api/v1/machines"},
	"listServices":       {Method: "GET", Path: "/api/v1/apps/{appId}/services"},
	"login":              {Method: "POST", Path: "/api/v1/auth/sessions"},
	"logout":             {Method: "DELETE", Path: "/api/v1/auth/sessions/current"},
	"me":                 {Method: "GET", Path: "/api/v1/auth/me"},
	"restartApplication": {Method: "POST", Path: "/api/v1/apps/{appId}/restart"},
	"rotateCSRF":         {Method: "GET", Path: "/api/v1/auth/csrf"},
	"startApplication":   {Method: "POST", Path: "/api/v1/apps/{appId}/start"},
	"stopApplication":    {Method: "POST", Path: "/api/v1/apps/{appId}/stop"},
	"streamJobEvents":    {Method: "GET", Path: "/api/v1/jobs/{jobId}/events/stream"},
	"streamLogs":         {Method: "GET", Path: "/api/v1/apps/{appId}/logs/stream"},
	"systemStatus":       {Method: "GET", Path: "/api/v1/system/status"},
}

var SchemaNames = []string{
	"Application",
	"ApplicationList",
	"BootstrapRequest",
	"BootstrapStatus",
	"CSRFResponse",
	"Capabilities",
	"CreateApplicationRequest",
	"Diagnostics",
	"DoctorCheck",
	"DoctorResponse",
	"HostResources",
	"InspectRequest",
	"InspectResponse",
	"Job",
	"JobEvent",
	"JobEventList",
	"JobList",
	"JobMutationResponse",
	"JobResponse",
	"LoginRequest",
	"Machine",
	"MachineList",
	"MeResponse",
	"Problem",
	"Service",
	"ServiceList",
	"SessionResponse",
	"SystemStatus",
	"User",
}
