package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      map[string]map[string]yaml.Node `yaml:"paths"`
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

type schema struct {
	Ref                  string            `yaml:"$ref"`
	Type                 string            `yaml:"type"`
	Format               string            `yaml:"format"`
	Required             []string          `yaml:"required"`
	Properties           map[string]schema `yaml:"properties"`
	Items                *schema           `yaml:"items"`
	AdditionalProperties yaml.Node         `yaml:"additionalProperties"`
}

type operation struct {
	ID     string
	Method string
	Path   string
}

func main() {
	check := flag.Bool("check", false, "fail if generated artifacts differ")
	specPath := flag.String("spec", "api/openapi.yaml", "OpenAPI source")
	goPath := flag.String("go", "internal/apicontract/generated.go", "generated Go artifact")
	tsPath := flag.String("ts", "web/src/generated/api-contract.ts", "generated TypeScript artifact")
	flag.Parse()

	source, err := os.ReadFile(*specPath)
	if err != nil {
		fatal(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fatal(fmt.Errorf("parse OpenAPI: %w", err))
	}
	operations, err := collectOperations(spec.Paths)
	if err != nil {
		fatal(err)
	}
	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goArtifact, err := renderGo(digest, operations, spec.Components.Schemas)
	if err != nil {
		fatal(err)
	}
	tsArtifact, err := renderTypeScript(digest, operations, spec.Components.Schemas)
	if err != nil {
		fatal(err)
	}
	for path, content := range map[string][]byte{*goPath: goArtifact, *tsPath: tsArtifact} {
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, content) {
				fatal(fmt.Errorf("generated contract drift: run go run ./cmd/openapi-gen (artifact %s)", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func collectOperations(paths map[string]map[string]yaml.Node) ([]operation, error) {
	var operations []operation
	seen := make(map[string]bool)
	for path, pathItem := range paths {
		for method, node := range pathItem {
			method = strings.ToUpper(method)
			if method != "GET" && method != "POST" && method != "PUT" && method != "PATCH" && method != "DELETE" {
				continue
			}
			var value struct {
				OperationID string `yaml:"operationId"`
			}
			if err := node.Decode(&value); err != nil {
				return nil, fmt.Errorf("decode %s %s: %w", method, path, err)
			}
			if value.OperationID == "" || seen[value.OperationID] {
				return nil, fmt.Errorf("missing or duplicate operationId for %s %s", method, path)
			}
			seen[value.OperationID] = true
			operations = append(operations, operation{ID: value.OperationID, Method: method, Path: path})
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].ID < operations[j].ID })
	return operations, nil
}

func renderGo(digest string, operations []operation, schemas map[string]schema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.\n\npackage apicontract\n\n")
	output.WriteString("type Operation struct { Method string; Path string }\n\n")
	fmt.Fprintf(&output, "const SourceSHA256 = %s\n\n", strconv.Quote(digest))
	output.WriteString("var Operations = map[string]Operation{\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "\t%s: {Method: %s, Path: %s},\n", strconv.Quote(operation.ID), strconv.Quote(operation.Method), strconv.Quote(operation.Path))
	}
	output.WriteString("}\n")
	for _, name := range sortedSchemaNames(schemas) {
		model := schemas[name]
		if err := validateObjectSchema(name, model); err != nil {
			return nil, err
		}
		fmt.Fprintf(&output, "\ntype %s struct {\n", name)
		required := stringSet(model.Required)
		for _, propertyName := range sortedPropertyNames(model.Properties) {
			property := model.Properties[propertyName]
			fieldType, err := goSchemaType(property)
			if err != nil {
				return nil, fmt.Errorf("schema %s property %s: %w", name, propertyName, err)
			}
			jsonName := propertyName
			if !required[propertyName] {
				jsonName += ",omitempty"
			}
			fmt.Fprintf(&output, "\t%s %s `json:%s`\n", exportedName(propertyName), fieldType, strconv.Quote(jsonName))
		}
		output.WriteString("}\n")
	}
	return format.Source([]byte(output.String()))
}

func renderTypeScript(digest string, operations []operation, schemas map[string]schema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const openAPISHA256 = %s;\n\n", strconv.Quote(digest))
	output.WriteString("export const operations = {\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "  %s: { method: %s, path: %s },\n", strconv.Quote(operation.ID), strconv.Quote(operation.Method), strconv.Quote(operation.Path))
	}
	output.WriteString("} as const;\n\nexport type OperationID = keyof typeof operations;\n\n")
	for _, name := range sortedSchemaNames(schemas) {
		model := schemas[name]
		if err := validateObjectSchema(name, model); err != nil {
			return nil, err
		}
		fmt.Fprintf(&output, "export type %s = {\n", name)
		required := stringSet(model.Required)
		for _, propertyName := range sortedPropertyNames(model.Properties) {
			propertyType, err := typeScriptSchemaType(model.Properties[propertyName])
			if err != nil {
				return nil, fmt.Errorf("schema %s property %s: %w", name, propertyName, err)
			}
			optional := ""
			if !required[propertyName] {
				optional = "?"
			}
			fmt.Fprintf(&output, "  %s%s: %s;\n", strconv.Quote(propertyName), optional, propertyType)
		}
		output.WriteString("};\n\n")
	}
	return []byte(strings.TrimRight(output.String(), "\n") + "\n"), nil
}

func sortedSchemaNames(schemas map[string]schema) []string {
	names := make([]string, 0, len(schemas))
	for name := range schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedPropertyNames(properties map[string]schema) []string {
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func stringSet(values []string) map[string]bool {
	set := make(map[string]bool, len(values))
	for _, value := range values {
		set[value] = true
	}
	return set
}

func validateObjectSchema(name string, model schema) error {
	if model.Type != "object" {
		return fmt.Errorf("schema %s: top-level type %q is not supported", name, model.Type)
	}
	for _, required := range model.Required {
		if _, ok := model.Properties[required]; !ok {
			return fmt.Errorf("schema %s: required property %q is not defined", name, required)
		}
	}
	return nil
}

func schemaReferenceName(ref string) (string, error) {
	const prefix = "#/components/schemas/"
	if !strings.HasPrefix(ref, prefix) || len(ref) == len(prefix) {
		return "", fmt.Errorf("unsupported reference %q", ref)
	}
	return strings.TrimPrefix(ref, prefix), nil
}

func goSchemaType(value schema) (string, error) {
	if value.Ref != "" {
		return schemaReferenceName(value.Ref)
	}
	switch value.Type {
	case "string":
		return "string", nil
	case "boolean":
		return "bool", nil
	case "integer":
		if value.Format == "int64" {
			return "int64", nil
		}
		return "int", nil
	case "number":
		return "float64", nil
	case "array":
		if value.Items == nil {
			return "", fmt.Errorf("array is missing items")
		}
		itemType, err := goSchemaType(*value.Items)
		if err != nil {
			return "", err
		}
		return "[]" + itemType, nil
	case "object":
		return goAdditionalPropertiesType(value.AdditionalProperties)
	default:
		return "", fmt.Errorf("unsupported type %q", value.Type)
	}
}

func typeScriptSchemaType(value schema) (string, error) {
	if value.Ref != "" {
		return schemaReferenceName(value.Ref)
	}
	switch value.Type {
	case "string":
		return "string", nil
	case "boolean":
		return "boolean", nil
	case "integer", "number":
		return "number", nil
	case "array":
		if value.Items == nil {
			return "", fmt.Errorf("array is missing items")
		}
		itemType, err := typeScriptSchemaType(*value.Items)
		if err != nil {
			return "", err
		}
		return itemType + "[]", nil
	case "object":
		return typeScriptAdditionalPropertiesType(value.AdditionalProperties)
	default:
		return "", fmt.Errorf("unsupported type %q", value.Type)
	}
}

func goAdditionalPropertiesType(node yaml.Node) (string, error) {
	if node.Kind == 0 || (node.Kind == yaml.ScalarNode && node.Value == "true") {
		return "map[string]any", nil
	}
	if node.Kind == yaml.ScalarNode && node.Value == "false" {
		return "map[string]any", nil
	}
	var additional schema
	if err := node.Decode(&additional); err != nil {
		return "", fmt.Errorf("decode additionalProperties: %w", err)
	}
	valueType, err := goSchemaType(additional)
	if err != nil {
		return "", err
	}
	return "map[string]" + valueType, nil
}

func typeScriptAdditionalPropertiesType(node yaml.Node) (string, error) {
	if node.Kind == 0 || (node.Kind == yaml.ScalarNode && node.Value == "true") {
		return "Record<string, unknown>", nil
	}
	if node.Kind == yaml.ScalarNode && node.Value == "false" {
		return "Record<string, never>", nil
	}
	var additional schema
	if err := node.Decode(&additional); err != nil {
		return "", fmt.Errorf("decode additionalProperties: %w", err)
	}
	valueType, err := typeScriptSchemaType(additional)
	if err != nil {
		return "", err
	}
	return "Record<string, " + valueType + ">", nil
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	if len(parts) == 0 {
		return "Field"
	}
	for index, part := range parts {
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	name := strings.Join(parts, "")
	if unicode.IsDigit([]rune(name)[0]) {
		name = "Field" + name
	}
	name = strings.ReplaceAll(name, "Id", "ID")
	name = strings.ReplaceAll(name, "Csrf", "CSRF")
	if name == "Os" {
		name = "OS"
	}
	if name == "Ok" {
		name = "OK"
	}
	return name
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
