package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      map[string]map[string]yaml.Node `yaml:"paths"`
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

type operation struct {
	ID     string
	Method string
	Path   string
}

func main() {
	check := flag.Bool("check", false, "fail if generated artifacts differ")
	specPath := flag.String("spec", "api/openapi.yaml", "OpenAPI source")
	goPath := flag.String("go", "internal/apicontract/generated.go", "generated Go artifact")
	tsPath := flag.String("ts", "web/src/generated/api-contract.ts", "generated TypeScript artifact")
	flag.Parse()

	source, err := os.ReadFile(*specPath)
	if err != nil {
		fatal(err)
	}
	var spec document
	if err := yaml.Unmarshal(source, &spec); err != nil {
		fatal(fmt.Errorf("parse OpenAPI: %w", err))
	}
	operations, err := collectOperations(spec.Paths)
	if err != nil {
		fatal(err)
	}
	schemas := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		schemas = append(schemas, name)
	}
	sort.Strings(schemas)
	digest := fmt.Sprintf("%x", sha256.Sum256(source))
	goArtifact, err := renderGo(digest, operations, schemas)
	if err != nil {
		fatal(err)
	}
	tsArtifact := renderTypeScript(digest, operations, schemas)
	for path, content := range map[string][]byte{*goPath: goArtifact, *tsPath: tsArtifact} {
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, content) {
				fatal(fmt.Errorf("generated contract drift: run go run ./cmd/openapi-gen (artifact %s)", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func collectOperations(paths map[string]map[string]yaml.Node) ([]operation, error) {
	var operations []operation
	seen := make(map[string]bool)
	for path, pathItem := range paths {
		for method, node := range pathItem {
			method = strings.ToUpper(method)
			if method != "GET" && method != "POST" && method != "PUT" && method != "PATCH" && method != "DELETE" {
				continue
			}
			var value struct {
				OperationID string `yaml:"operationId"`
			}
			if err := node.Decode(&value); err != nil {
				return nil, fmt.Errorf("decode %s %s: %w", method, path, err)
			}
			if value.OperationID == "" || seen[value.OperationID] {
				return nil, fmt.Errorf("missing or duplicate operationId for %s %s", method, path)
			}
			seen[value.OperationID] = true
			operations = append(operations, operation{ID: value.OperationID, Method: method, Path: path})
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].ID < operations[j].ID })
	return operations, nil
}

func renderGo(digest string, operations []operation, schemas []string) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.\n\npackage apicontract\n\n")
	output.WriteString("type Operation struct { Method string; Path string }\n\n")
	fmt.Fprintf(&output, "const SourceSHA256 = %s\n\n", strconv.Quote(digest))
	output.WriteString("var Operations = map[string]Operation{\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "\t%s: {Method: %s, Path: %s},\n", strconv.Quote(operation.ID), strconv.Quote(operation.Method), strconv.Quote(operation.Path))
	}
	output.WriteString("}\n\nvar SchemaNames = []string{\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "\t%s,\n", strconv.Quote(schema))
	}
	output.WriteString("}\n")
	return format.Source([]byte(output.String()))
}

func renderTypeScript(digest string, operations []operation, schemas []string) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by go run ./cmd/openapi-gen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const openAPISHA256 = %s;\n\n", strconv.Quote(digest))
	output.WriteString("export const operations = {\n")
	for _, operation := range operations {
		fmt.Fprintf(&output, "  %s: { method: %s, path: %s },\n", strconv.Quote(operation.ID), strconv.Quote(operation.Method), strconv.Quote(operation.Path))
	}
	output.WriteString("} as const;\n\nexport type OperationID = keyof typeof operations;\n\n")
	output.WriteString("export const schemaNames = [\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "  %s,\n", strconv.Quote(schema))
	}
	output.WriteString("] as const;\n\nexport type SchemaName = (typeof schemaNames)[number];\n")
	return []byte(output.String())
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
